coloc_movies_choice:
    resource: "@ColocMoviesBundle/Controller/ChoiceController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"